# Lab 2 – Tensors
#### pytorch-tensors

In [ ]:
# Import PyTorch
import torch

## Create empty tensors
- Uninitialised tensors

In [ ]:
# 1-D
x = torch.empty(1) #쓰레기값
print(x)

# 1-D with two elements
x = torch.empty(2)
print(f"\n1-D tensor\n{x}\n")

# 2-D
x = torch.empty(2,3)
print(f"2-D tensor\n{x}\n")

# 3-D
x = torch.empty(2,3,1)
print("3-D tensor\n",x)


tensor([5.7604e+09])

1-D tensor
tensor([2.2074e-35, 0.0000e+00])

2-D tensor
tensor([[2.2091e-35, 0.0000e+00, 2.2092e-35],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

3-D tensor
 tensor([[[2.2097e-35],
         [0.0000e+00],
         [2.2096e-35]],

        [[0.0000e+00],
         [1.4013e-45],
         [0.0000e+00]]])


## Initialise tensors to scalar, random values, zeros or ones

In [ ]:
# 0-D tensor (just containing scalar value 3)
x = torch.tensor(3)
# print(x)
print(f'Scalar: {x} has shape {x.shape} and {x.ndim} dimensions\n')

# Random values in the interval [0,1]
x = torch.rand(2,3)
print(f"Random values:\n{x}")
print(x.dtype)

# Zeros
x = torch.zeros(2,3)
print(f"\nZeros:\n{x}")
print(x.dtype)

x = torch.zeros(2,3, dtype=torch.int)
print(f"\nZeros:\n{x}\n")

# Ones
x = torch.ones(2,3)
print(f"Ones:\n{x}")
print(f"Type: {x.dtype}\n")

x = torch.ones(2,3, dtype=torch.double)
print(f"Ones:\n{x}")

Scalar: 3 has shape torch.Size([]) and 0 dimensions

Random values:
tensor([[0.3412, 0.1209, 0.8308],
        [0.8335, 0.0817, 0.3631]])
torch.float32

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32

Zeros:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.float32

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## Construct tensor from data

In [ ]:
# Change a list to a tensor
x = torch.tensor([0.5, 2.7])
print(x)

tensor([0.5000, 2.7000])


### Changing tensor data type


In [ ]:
x = torch.rand(2,3) * 20
print(x)

# Change to integer
y = x.to(torch.int32)
print(y)

tensor([[14.7458,  1.6789, 17.3969],
        [ 6.6529,  7.0464, 10.7259]])
tensor([[14,  1, 17],
        [ 6,  7, 10]], dtype=torch.int32)


### Create a separate copy



In [ ]:
a = torch.ones(2, 2)
b = a.clone()

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[1., 1.],
        [1., 1.]])


## Basic tensor operations

- addition, subtraction, multiplication, division

In [ ]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

z = torch.add(x,y) # same as z = x + y
print("x + y = ")
print(z)

z = torch.sub(x,y) # same as z = x - y
print("x - y = ")
print(z)

z = torch.mul(x,y) # same as z = x * y
print("x * y = ")
print(z)

z = torch.div(x,y) # same as z = x / y
print("x / y = ")
print(z)


x = 
tensor([[0.2727, 0.7014],
        [0.3221, 0.2855]])

y = 
tensor([[0.4770, 0.5040],
        [0.5897, 0.4181]])

x + y = 
tensor([[0.7497, 1.2054],
        [0.9118, 0.7035]])
x - y = 
tensor([[-0.2043,  0.1974],
        [-0.2675, -0.1326]])
x * y = 
tensor([[0.1301, 0.3535],
        [0.1899, 0.1194]])
x / y = 
tensor([[0.5718, 1.3916],
        [0.5463, 0.6829]])


### Inplace operations

- any function with a trailing underscore (e.g. ``add_``) will modify the value of the variable in question, in place

In [ ]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

# Inplace operations
y.add_(x) # modify y by adding x to it
print(f"y + x = {y}")

y.sub_(x) # modify y by subtracting x from it
print(f"y - x = {y}")

y.mul_(x) # modify y by multiplying x to it
print(f"y * x = {y}")

y.div_(x) # modify y by dividing it by x
print(f"y / x = {y}")


x = 
tensor([[0.6178, 0.9606],
        [0.8036, 0.6479]])

y = 
tensor([[0.0376, 0.2728],
        [0.9558, 0.8381]])

y + x = tensor([[0.6554, 1.2335],
        [1.7594, 1.4860]])
y - x = tensor([[0.0376, 0.2728],
        [0.9558, 0.8381]])
y * x = tensor([[0.0232, 0.2621],
        [0.7681, 0.5430]])
y / x = tensor([[0.0376, 0.2728],
        [0.9558, 0.8381]])


## Accessing tensors

In [ ]:
# Slicing
x = torch.rand(5,3)
print(x)

# Get all rows but only first column
print(x[:, 0])

# Get all columns but only the second row
print(x[1, :])

# Get a specific element
print(x[2,2])

# When the tensor returns only ONE element, use item() to get the actual value of that element
print(x[1,1].item())

y = torch.tensor([2.0])
print(y.item())

tensor([[0.9526, 0.3876, 0.3230],
        [0.7011, 0.7489, 0.9945],
        [0.4169, 0.8741, 0.8831],
        [0.2630, 0.2240, 0.1538],
        [0.8018, 0.6669, 0.6085]])
tensor([0.9526, 0.7011, 0.4169, 0.2630, 0.8018])
tensor([0.7011, 0.7489, 0.9945])
tensor(0.8831)
0.7489154934883118
2.0


## Tensor Shape & Dimensions
- The number of dimensions a tensor has is called its rank and the length in each dimension describes its ``shape``.
- To determine the length of each dimension, call ``.shape``
- To determine the number of dimensions it has, call ``.ndim``


In [ ]:
x = torch.rand(5,3)
print(f'{x} \nhas shape {x.shape} and {x.ndim} dimensions\n')

tensor([[0.3797, 0.1953, 0.6296],
        [0.7235, 0.3492, 0.1825],
        [0.6619, 0.9438, 0.0408],
        [0.4771, 0.8730, 0.8290],
        [0.7999, 0.3344, 0.0175]]) 
has shape torch.Size([5, 3]) and 2 dimensions



## More on Shapes

- `[1,5,2,6]` has shape (4,) to indicate it has 4 elements and the missing element after the comma means it is a 1-D tensor or array (vector)
- `[[1,5,2,6], [1,2,3,1]]` has shape (2,4) to indicate it has 2 elements (rows) and each of these have 4 elements (columns). This is a 2-D tensor or array (matrix or a list of vectors)
- `[[[1,5,2,6], [1,2,3,1]], [[5,2,1,2], [6,4,3,2]], [[7,8,5,3], [2,2,9,6]]]` has shape (3, 2, 4) to indicate it has 3 elements in the first dimension, and each of these contain 2 elements and each of these contain 4 elements. This is a 3-D tensor or array


## Operations on tensor dimensions
- A tensor dimension is akin to an array's axis. The number of dimensions is called rank.
- A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a cuboid has rank 3, etc.
- Sometimes one wants to do an operation only on a particular dimension, e.g. on the rows only
- Across ``dim=X`` means we do the operation w.r.t to the dimension given and the rest of the dimensions of the tensor stays as they are
- in 2-D tensors, ``dim=0`` refers to the columns while ``dim=1`` refers to the rows


In [ ]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

print(x.shape)
print(f'Summing across dim=0 (columns) gives: {torch.sum(x,dim=0)}')

print(f'Summing across dim=1 (rows) gives: {torch.sum(x,dim=1)}')


torch.Size([2, 3])
Summing across dim=0 (columns) gives: tensor([5, 7, 9])
Summing across dim=1 (rows) gives: tensor([ 6, 15])


## Reshaping tensors
- There are several ways to do this but using ``torch.reshape()`` is the most common
- Also look up ``torch.squeeze(), torch.unsqueeze()`` and ``torch.view()``


In [ ]:
x = torch.rand(4,4)
print("Original:")
print(x)
print(x.shape)

# Reshape (flatten) to 1-D
y = x.reshape(16) # number of elements must be the same as original, error otherwise
print("Reshaped to 1-D:")
print(y)

# Reshape to 2-D
y = x.reshape(8,2)
print("Reshaped to 2-D:")
print(y)

# Could leave out one of the dimensions by specifying -1
y = x.reshape(2, -1)
print("Reshaped to 2 x Unspecified 2-D:")
print(y)
print(y.shape)

# Could use unsqueeze(0) to add a dimension at position 0
y = x.unsqueeze(0)
print(f'Using unsqueeze(0) to add dimension from original shape {x.shape} to {y.shape}')

Original:
tensor([[0.1864, 0.3683, 0.8342, 0.3858],
        [0.2672, 0.2293, 0.0567, 0.9322],
        [0.9314, 0.5012, 0.5854, 0.2795],
        [0.1222, 0.1359, 0.0690, 0.2150]])
torch.Size([4, 4])
Reshaped to 1-D:
tensor([0.1864, 0.3683, 0.8342, 0.3858, 0.2672, 0.2293, 0.0567, 0.9322, 0.9314,
        0.5012, 0.5854, 0.2795, 0.1222, 0.1359, 0.0690, 0.2150])
Reshaped to 2-D:
tensor([[0.1864, 0.3683],
        [0.8342, 0.3858],
        [0.2672, 0.2293],
        [0.0567, 0.9322],
        [0.9314, 0.5012],
        [0.5854, 0.2795],
        [0.1222, 0.1359],
        [0.0690, 0.2150]])
Reshaped to 2 x Unspecified 2-D:
tensor([[0.1864, 0.3683, 0.8342, 0.3858, 0.2672, 0.2293, 0.0567, 0.9322],
        [0.9314, 0.5012, 0.5854, 0.2795, 0.1222, 0.1359, 0.0690, 0.2150]])
torch.Size([2, 8])
Using unsqueeze(0) to add dimension from original shape torch.Size([4, 4]) to torch.Size([1, 4, 4])


## Convert between NumPy and PyTorch tensors

- Tensors can work on CPUs and GPUs
- NumPy arrays can only work on CPUs

In [ ]:
import torch
import numpy as np

# Tensor to NumPy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# b changes when a is modified because they share the same memory space!
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

# Modifying array will modify the tensor as well
a += 2
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# Exercise

In [ ]:
# 1. Create a tensor of 100 equally spaced numbers from 0 to 2.
# Assign the tensor to x (Hint: use torch.linspace() )
x = torch.linspace(0, 2, 100)
# Print x
print(x)

tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808, 0.1010, 0.1212, 0.1414, 0.1616,
        0.1818, 0.2020, 0.2222, 0.2424, 0.2626, 0.2828, 0.3030, 0.3232, 0.3434,
        0.3636, 0.3838, 0.4040, 0.4242, 0.4444, 0.4646, 0.4848, 0.5051, 0.5253,
        0.5455, 0.5657, 0.5859, 0.6061, 0.6263, 0.6465, 0.6667, 0.6869, 0.7071,
        0.7273, 0.7475, 0.7677, 0.7879, 0.8081, 0.8283, 0.8485, 0.8687, 0.8889,
        0.9091, 0.9293, 0.9495, 0.9697, 0.9899, 1.0101, 1.0303, 1.0505, 1.0707,
        1.0909, 1.1111, 1.1313, 1.1515, 1.1717, 1.1919, 1.2121, 1.2323, 1.2525,
        1.2727, 1.2929, 1.3131, 1.3333, 1.3535, 1.3737, 1.3939, 1.4141, 1.4343,
        1.4545, 1.4747, 1.4949, 1.5152, 1.5354, 1.5556, 1.5758, 1.5960, 1.6162,
        1.6364, 1.6566, 1.6768, 1.6970, 1.7172, 1.7374, 1.7576, 1.7778, 1.7980,
        1.8182, 1.8384, 1.8586, 1.8788, 1.8990, 1.9192, 1.9394, 1.9596, 1.9798,
        2.0000])


In [ ]:
# 2. Print the first 5 numbers in x.
print(x[:5])
# 3. Print the last 5 numbers in x
print(x[-5:])

tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808])
tensor([1.9192, 1.9394, 1.9596, 1.9798, 2.0000])


In [ ]:
# 4. Create another tensor of 100 random values between 0 and 1.
# Assign the tensor to y (Hint: use torch.rand() )
y = torch.rand(1, 100)
# Print y
print(y)

tensor([[0.1735, 0.9593, 0.7266, 0.7268, 0.4818, 0.3169, 0.8533, 0.4336, 0.1107,
         0.0331, 0.4211, 0.6872, 0.4350, 0.9811, 0.4179, 0.9524, 0.3146, 0.9040,
         0.6316, 0.4206, 0.9388, 0.8176, 0.8686, 0.6100, 0.5933, 0.7473, 0.2082,
         0.9493, 0.1702, 0.6679, 0.0885, 0.2490, 0.9907, 0.0357, 0.3263, 0.7342,
         0.2271, 0.2732, 0.3218, 0.5868, 0.1932, 0.2418, 0.0872, 0.5513, 0.6358,
         0.3541, 0.0291, 0.6873, 0.4842, 0.9223, 0.7953, 0.8473, 0.5804, 0.8737,
         0.4754, 0.4356, 0.0099, 0.2714, 0.4012, 0.8267, 0.4926, 0.5222, 0.3081,
         0.0212, 0.4361, 0.8586, 0.6720, 0.1211, 0.9082, 0.2191, 0.7422, 0.6165,
         0.0762, 0.7842, 0.4208, 0.0333, 0.3986, 0.1493, 0.0355, 0.4042, 0.3876,
         0.2324, 0.0540, 0.4755, 0.3141, 0.7170, 0.2375, 0.2146, 0.6774, 0.6307,
         0.4235, 0.0639, 0.1558, 0.9636, 0.2892, 0.8850, 0.1579, 0.7469, 0.9941,
         0.1498]])


In [ ]:
# 5. Multiply x and y, store the result in z
z = x*y
# Print z
print(z)

tensor([[0.0000, 0.0194, 0.0294, 0.0440, 0.0389, 0.0320, 0.1034, 0.0613, 0.0179,
         0.0060, 0.0851, 0.1527, 0.1054, 0.2577, 0.1182, 0.2886, 0.1017, 0.3105,
         0.2297, 0.1614, 0.3793, 0.3468, 0.3860, 0.2834, 0.2876, 0.3774, 0.1094,
         0.5178, 0.0963, 0.3913, 0.0536, 0.1559, 0.6404, 0.0238, 0.2242, 0.5191,
         0.1652, 0.2042, 0.2470, 0.4623, 0.1561, 0.2003, 0.0740, 0.4789, 0.5651,
         0.3219, 0.0270, 0.6526, 0.4695, 0.9130, 0.8034, 0.8730, 0.6097, 0.9355,
         0.5186, 0.4839, 0.0112, 0.3125, 0.4700, 0.9853, 0.5971, 0.6435, 0.3859,
         0.0269, 0.5638, 1.1275, 0.8960, 0.1639, 1.2477, 0.3053, 1.0496, 0.8842,
         0.1108, 1.1565, 0.6290, 0.0505, 0.6120, 0.2323, 0.0560, 0.6450, 0.6264,
         0.3802, 0.0895, 0.7972, 0.5330, 1.2312, 0.4126, 0.3771, 1.2042, 1.1340,
         0.7700, 0.1175, 0.2896, 1.8103, 0.5492, 1.6985, 0.3062, 1.4637, 1.9681,
         0.2996]])


In [ ]:
# 6. Reshape z to a tensor with 5 rows and 20 columns
# Store reshaped tensor to z2
z2 = z.reshape(5, -1)
# Print z2
print(z2)

tensor([[0.0000, 0.0194, 0.0294, 0.0440, 0.0389, 0.0320, 0.1034, 0.0613, 0.0179,
         0.0060, 0.0851, 0.1527, 0.1054, 0.2577, 0.1182, 0.2886, 0.1017, 0.3105,
         0.2297, 0.1614],
        [0.3793, 0.3468, 0.3860, 0.2834, 0.2876, 0.3774, 0.1094, 0.5178, 0.0963,
         0.3913, 0.0536, 0.1559, 0.6404, 0.0238, 0.2242, 0.5191, 0.1652, 0.2042,
         0.2470, 0.4623],
        [0.1561, 0.2003, 0.0740, 0.4789, 0.5651, 0.3219, 0.0270, 0.6526, 0.4695,
         0.9130, 0.8034, 0.8730, 0.6097, 0.9355, 0.5186, 0.4839, 0.0112, 0.3125,
         0.4700, 0.9853],
        [0.5971, 0.6435, 0.3859, 0.0269, 0.5638, 1.1275, 0.8960, 0.1639, 1.2477,
         0.3053, 1.0496, 0.8842, 0.1108, 1.1565, 0.6290, 0.0505, 0.6120, 0.2323,
         0.0560, 0.6450],
        [0.6264, 0.3802, 0.0895, 0.7972, 0.5330, 1.2312, 0.4126, 0.3771, 1.2042,
         1.1340, 0.7700, 0.1175, 0.2896, 1.8103, 0.5492, 1.6985, 0.3062, 1.4637,
         1.9681, 0.2996]])


In [ ]:
# 7. Get the sum of each row in z2
print(z2.sum(axis = 1))
# 8. Get the mean of each column in z2
print(z2.sum(axis = 0))

tensor([ 2.1634,  5.8712,  9.8617, 11.3836, 16.0582])
tensor([1.7590, 1.5902, 0.9647, 1.6306, 1.9886, 3.0901, 1.5484, 1.7728, 3.0356,
        2.7496, 2.7617, 2.1833, 1.7559, 4.1838, 2.0392, 3.0407, 1.1962, 2.5233,
        2.9708, 2.5537])


In [ ]:
print(z2.sum(dim = 0))

tensor([1.7590, 1.5902, 0.9647, 1.6306, 1.9886, 3.0901, 1.5484, 1.7728, 3.0356,
        2.7496, 2.7617, 2.1833, 1.7559, 4.1838, 2.0392, 3.0407, 1.1962, 2.5233,
        2.9708, 2.5537])


In [ ]:
# 9. Reshape z to a 3D tensor (keep all the elements)
# Store reshaped tensor to z3
z3 = z.reshape(2, 5, -1)
# Print z3
print(z3)

tensor([[[0.0000, 0.0194, 0.0294, 0.0440, 0.0389, 0.0320, 0.1034, 0.0613,
          0.0179, 0.0060],
         [0.0851, 0.1527, 0.1054, 0.2577, 0.1182, 0.2886, 0.1017, 0.3105,
          0.2297, 0.1614],
         [0.3793, 0.3468, 0.3860, 0.2834, 0.2876, 0.3774, 0.1094, 0.5178,
          0.0963, 0.3913],
         [0.0536, 0.1559, 0.6404, 0.0238, 0.2242, 0.5191, 0.1652, 0.2042,
          0.2470, 0.4623],
         [0.1561, 0.2003, 0.0740, 0.4789, 0.5651, 0.3219, 0.0270, 0.6526,
          0.4695, 0.9130]],

        [[0.8034, 0.8730, 0.6097, 0.9355, 0.5186, 0.4839, 0.0112, 0.3125,
          0.4700, 0.9853],
         [0.5971, 0.6435, 0.3859, 0.0269, 0.5638, 1.1275, 0.8960, 0.1639,
          1.2477, 0.3053],
         [1.0496, 0.8842, 0.1108, 1.1565, 0.6290, 0.0505, 0.6120, 0.2323,
          0.0560, 0.6450],
         [0.6264, 0.3802, 0.0895, 0.7972, 0.5330, 1.2312, 0.4126, 0.3771,
          1.2042, 1.1340],
         [0.7700, 0.1175, 0.2896, 1.8103, 0.5492, 1.6985, 0.3062, 1.4637,
          1.968